# Generated by Django 5.1.1 on 2024-10-03 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_company_phone_alter_user_is_company_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_large',
            field=models.ImageField(upload_to='logos/large/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo_small',
            field=models.ImageField(upload_to='logos/small/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
