# Generated by Django 5.1.1 on 2024-10-04 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_company_logo_large_alter_company_logo_small'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
