# Generated by Django 5.1.1 on 2024-10-11 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_company_background_color_company_primary_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='landing_type',
        ),
        migrations.AddField(
            model_name='company',
            name='general_data_for_products',
            field=models.TextField(blank=True, help_text='General data that will be shown in each product of page', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.TextField(default='Envio gratuito, Llega en dos dias o menos!', help_text='The features of the product. Separate each feature with a comma.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='background_color',
            field=models.CharField(help_text='The color in hexadesimal', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='primary_color',
            field=models.CharField(help_text='The color in hexadesimal (darker)', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='secondary_color',
            field=models.CharField(help_text='The color in hexadesimal (lighter)', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='text_color',
            field=models.CharField(help_text='The color in hexadesimal', max_length=7),
        ),
        migrations.AlterField(
            model_name='company',
            name='whatsapp_message',
            field=models.CharField(blank=True, help_text='The message that will be sent by the user to the company', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='The image of the product (horizontal orientation with main part at the right))', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
