# Generated by Django 5.1.2 on 2024-10-23 17:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_appointment_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='appointment_duration',
            field=models.FloatField(default=0.25, help_text='Duration of each appointment in hours (e.g., 0.25 for 15 minutes)', validators=[django.core.validators.RegexValidator(message='Duration must be 0.25, 0.5, or 1 hour.', regex='^(0\\.25|0\\.5|1)$')]),
        ),
        migrations.AddField(
            model_name='company',
            name='appointment_end_time',
            field=models.IntegerField(default=20, help_text='End time for appointments (e.g., 20 for 8 PM)'),
        ),
        migrations.AddField(
            model_name='company',
            name='appointment_start_time',
            field=models.IntegerField(default=8, help_text='Start time for appointments (e.g., 8 for 8 AM)'),
        ),
        migrations.AddField(
            model_name='company',
            name='off_days_of_the_week',
            field=models.JSONField(default=[7, 1], help_text='List of off days of the week (e.g., [7, 1] for Sunday and Saturday)'),
        ),
        migrations.AddField(
            model_name='company',
            name='off_hours',
            field=models.JSONField(default=[12, 13, 14], help_text='List of off hours (e.g., [12, 13, 14] for 12 PM, 1 PM, and 2 PM)'),
        ),
    ]
