# Generated by Django 5.1.2 on 2024-10-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_company_appointment_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='enable_appointments',
            field=models.BooleanField(default=True, help_text='Enable or disable appointments (calendar)'),
        ),
    ]
