# Generated by Django 5.1.2 on 2024-10-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_appointment_cancel_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='appointment_end_time',
            field=models.TimeField(default='20:00', help_text='End time for appointments (e.g., 20:00 for 8 PM)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='appointment_start_time',
            field=models.TimeField(default='08:00', help_text='Start time for appointments (e.g., 08:00 for 8 AM)'),
        ),
    ]
