# Generated by Django 5.1.2 on 2024-10-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_company_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='appointment_end_time',
            field=models.IntegerField(default=20, help_text='End time for appointments (e.g., 20 for 8 PM)'),
        ),
        migrations.AlterField(
            model_name='company',
            name='appointment_start_time',
            field=models.IntegerField(default=8, help_text='Start time for appointments (e.g., 8 for 8 AM)'),
        ),
    ]
