# Generated by Django 5.1.2 on 2024-10-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_company_appointment_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_utc_offset',
            field=models.IntegerField(default=-5, help_text='The UTC offset of the country of the company (colombia is -5)'),
        ),
    ]
