# Generated by Django 5.1.2 on 2024-11-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_company_country_utc_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='product_description',
            field=models.TextField(blank=True, help_text='The description of the products of the company', null=True),
        ),
    ]
